version: '3.1'

services:
    web:
        image: docker-swarm-demo-web
        build:
            context: .
            dockerfile: deployment/Dockerfile.web
        command: 'python app.py'
        links:
            - redis
        ports:
            - 5000:5000
        deploy:
            mode: replicated
            replicas: 2
            placement:
                constraints:
                    - node.labels.api == true
        volumes:
            - .:/home/docker/code

    nginx:
        image: docker-swarm-demo-nginx
        build:
            context: .
            dockerfile: deployment/Dockerfile.nginx
        ports:
            - 8001:80
        links:
            - web
        deploy:
            mode: replicated
            replicas: 1
            placement:
                constraints:
                    - node.labels.nginx == true

    redis:
        image: redis
        deploy:
            replicas: 1
            placement:
                constraints: [node.role == manager]
secrets:
    db_password:
        external: true